### use balance
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "0609213364",
  "amount": 100
}

### use balance2
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "0036675819",
  "amount": 123
}

### cancel balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId": "ae3858f0558f4b1484b2e830179e5449",
  "accountNumber": "0036675819",
  "amount": 123
}

### query transaction
GET http://localhost:8080/transaction/58452bcf5d0c407bad80619848918b23
