### create account
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000000",
  "amount": 123
}

### cancel balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId": "a4df4a23f10143e38dd27fe383032671",
  "accountNumber": "1000000000",
  "amount": 123
}
