### use balance
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "6610472707",
  "amount": 100
}

### use balance2
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "6610472707",
  "amount": 123
}

### cancel balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId": "fcce5f44f8ce4f2d90a41cddf8afa5ca",
  "accountNumber": "7686317186",
  "amount": 99900
}

### query transaction
GET http://localhost:8080/transaction/2449a31b7f3a40dbab7284a0664dda9e
