### GET request with a header
GET http://localhost:8080/csrf
Content-Type: application/json

### POST request with a header
POST http://localhost:8080/csrf
Content-Type: application/json

### POST request with a header
POST http://localhost:8080/csrf
Content-Type: application/x-www-form-urlencoded

_csrf = IIf4tkE9WTN94AZ5MYW0pD22Cr1ajy-6mW6X3bR7TWi6qjmLE7XAg3kPYVVQ2DVBB6iAlQ7UJ4VsuRyXqAyu5dcZK1uPyVq6

### Send GET request with json body
GET http://localhost:8080/csrfToken
Content-Type: application/json