spring:
  datasource:
    url: jdbc:mysql://localhost:3307/elastic
    username: root
    password: focandlol1!
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  elasticsearch:
    uris: http://localhost:9200

logging:
  level:
    org.elasticsearch.client: TRACE